services:
  web:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        REPO_URL: github.com/vandersoncurty/Eclipse_rebirth.git
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
